apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: loki
  namespace: grafana
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: '5.41.6'
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: grafana
      interval: 1m
  values:
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: 'filesystem'
    singleBinary:
      replicas: 1
