apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: promtail
  namespace: grafana
spec:
  interval: 5m
  chart:
    spec:
      chart: promtail
      version: '6.15.3'
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: grafana
      interval: 1m
